ARG COMPOSER_AUTH

CMD ["/magento.sh"]

COPY . /

ENV MAGENTO_VERSION=${MAGENTO_VERSION} \
    NGINX_CONF=magento \
    ENABLE_REDIS=On \
    PHP_OPCACHE_VALIDATE=Off

RUN composer create-project --no-interaction --prefer-dist --no-dev --repository=https://repo.magento.com/ magento/project-community-edition ${WEB_ROOT} ${MAGENTO_VERSION} && \
    composer require outeredge/magento-disable-common && \
    composer clear-cache && \
    sed -i '/^#/d' ${WEB_ROOT}/nginx.conf.sample && \
    sed -i '/memory_limit/d' ${WEB_ROOT}/nginx.conf.sample && \
    sed -i 's/|health_check/|health_check|search/g' ${WEB_ROOT}/nginx.conf.sample && \
    sed -i 's/php-fpm:9000/fastcgi_backend/g' ${WEB_ROOT}/nginx.conf.sample && \
    sed -i "/fastcgi_backend/a \
        fastcgi_param MAGE_MODE \$MAGE_MODE if_not_empty; \
        fastcgi_param MAGE_RUN_CODE \$MAGE_RUN_CODE if_not_empty;" ${WEB_ROOT}/nginx.conf.sample && \
    sudo cp ${WEB_ROOT}/nginx.conf.sample /templates/magento.conf.j2
