ARG COMPOSER_AUTH

CMD ["/magento.sh"]

RUN sudo apt-get update \
    && sudo rm -Rf /etc/php/$PHP_VERSION/cli \
    && sudo apt-get install --no-install-recommends --yes \
        imagemagick \
        sassc \
        php${PHP_VERSION}-gd \
        php${PHP_VERSION}-imagick \
    && sudo rm -Rf /etc/php/$PHP_VERSION/cli \
    && sudo ln -s /etc/php/$PHP_VERSION/fpm /etc/php/$PHP_VERSION/cli \
    && sudo rm -rf /var/lib/apt/lists/*

COPY . /

ENV MAGENTO_VERSION=${MAGENTO_VERSION} \
    NGINX_CONF=magento \
    ENABLE_REDIS=On

RUN cp /composer.json . && \
    sudo rm /composer.json && \
    composer require --update-no-dev magento/product-community-edition ${MAGENTO_VERSION} && \
    composer install --no-interaction --prefer-dist --no-dev && \
    composer clear-cache && \
    sed -i '/^#/d' ${WEB_ROOT}/nginx.conf.sample && \
    sed -i '/memory_limit/d' ${WEB_ROOT}/nginx.conf.sample && \
    sed -i 's/|health_check/|health_check|search/g' ${WEB_ROOT}/nginx.conf.sample && \
    sed -i "/fastcgi_backend/a \
        fastcgi_param MAGE_MODE \$MAGE_MODE if_not_empty; \
        fastcgi_param MAGE_RUN_CODE \$MAGE_RUN_CODE if_not_empty;" ${WEB_ROOT}/nginx.conf.sample && \
    sudo cp ${WEB_ROOT}/nginx.conf.sample /templates/magento.conf.j2
